### ISSUE TITLE
Cannot Locate .iso Files

### ISSUE THREAD

**Issue by redman922** [developersu/Tihwin#9]
Hi! I was able to open Tihwin and have an .iso file ready on my Downloads folder, and when I try to locate it after going to Downloads, it's not showing anything. It's my first time doing this so maybe I still need to do something else before I can fully use it? Please advise. Thank you so much in advance! 
![Screen Shot 2023-09-07 at 6 16 22 AM](https://github.com/developersu/Tihwin/assets/144340263/6a3d7c08-82f4-4909-9430-a4c786c83385)
![Screen Shot 2023-09-07 at 6 16 47 AM](https://github.com/developersu/Tihwin/assets/144340263/e6affaca-7da9-4b89-b10d-25b7cc22d7b7)

**Comment by developersu** [comment]
Hi! I guess it's some kind of Java runtime issue. Try using different one like Azul JDK 20 or Oracle JDK 11 or just any other one.
Because I don't see any issues in code.. can [add drag-n-drop support](https://redrise.ru/builds/Tihwin/Tihwin-2.4-20230908.191116.jar) as a workaround but it should not work like this. Also you should see folders in this window-selector and there are none.
Thanks!

**Comment by redman922** [comment]
Hi! I tried installing Azul JDK 20 or Oracle JDK 11 and other types but it just doesn't seem to work for me. Although the drag and drop feature you gave worked like a charm! Thank you so much for taking the time to help! Your work is amazing. I'll make sure to spread this to other enthusiasts I know in social media.
